### ISSUE TITLE
ERROR in node_modules/ng-multiselect-dropdown/click-outside.directive.d.ts:8:21 - error TS2694: Namespace '"../node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

### ISSUE THREAD

**Issue by masthanshaik675** [NileshPatel17/ng-multiselect-dropdown#421]
**Angular version**: 9

**ng-multiselect-dropdown version**: 1.0.0

**Description of issue**:  Initially we are using ng-multiselect-dropdown version 0.3.1 , After upgrade to 1.0.0 , after we run  - npm run start command , started getting the compilation errors-

ERROR in node_modules/ng-multiselect-dropdown/click-outside.directive.d.ts:8:21 - error TS2694: Namespace '"C:/MSDE/masthans/Hulk_UI/bifrost_hulk_new_1/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

8     static ɵfac: i0.ɵɵFactoryDeclaration<ClickOutsideDirective, never>;
                      ~~~~~~~~~~~~~~~~~~~~
node_modules/ng-multiselect-dropdown/click-outside.directive.d.ts:9:21 - error TS2694: Namespace '"C:/MSDE/masthans/Hulk_UI/bifrost_hulk_new_1/node_modules/@angular/core/core"' has no exported member 'ɵɵDirectiveDeclaration'.

9     static ɵdir: i0.ɵɵDirectiveDeclaration<ClickOutsideDirective, "[clickOutside]", never, {}, { "clickOutside": "clickOutside"; }, never, never, false, 
never>;
                      ~~~~~~~~~~~~~~~~~~~~~~
node_modules/ng-multiselect-dropdown/list-filter.pipe.d.ts:7:21 - error TS2694: Namespace '"C:/MSDE/masthans/Hulk_UI/bifrost_hulk_new_1/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

7     static ɵfac: i0.ɵɵFactoryDeclaration<ListFilterPipe, never>;
                      ~~~~~~~~~~~~~~~~~~~~
node_modules/ng-multiselect-dropdown/list-filter.pipe.d.ts:8:22 - error TS2694: Namespace '"C:/MSDE/masthans/Hulk_UI/bifrost_hulk_new_1/node_modules/@angular/core/core"' has no exported member 'ɵɵPipeDeclaration'.

8     static ɵpipe: i0.ɵɵPipeDeclaration<ListFilterPipe, "multiSelectFilter", false>;
                       ~~~~~~~~~~~~~~~~~
node_modules/ng-multiselect-dropdown/multiselect.component.d.ts:52:21 - error TS2694: Namespace '"C:/MSDE/masthans/Hulk_UI/bifrost_hulk_new_1/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

52     static ɵfac: i0.ɵɵFactoryDeclaration<MultiSelectComponent, never>;
                       ~~~~~~~~~~~~~~~~~~~~
node_modules/ng-multiselect-dropdown/multiselect.component.d.ts:53:21 - error TS2694: Namespace '"C:/MSDE/masthans/Hulk_UI/bifrost_hulk_new_1/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.

53     static ɵcmp: i0.ɵɵComponentDeclaration<MultiSelectComponent, "ng-multiselect-dropdown", never, { "placeholder": { "alias": "placeholder"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; "settings": { "alias": "settings"; "required": false; }; "data": { "alias": "data"; "required": false; }; }, { "onFilterChange": "onFilterChange"; "onDropDownClose": "onDropDownClose"; "onSelect": "onSelect"; "onDeSelect": "onDeSelect"; "onSelectAll": "onSelectAll"; "onDeSelectAll": "onDeSelectAll"; }, never, never, false, never>;
                       ~~~~~~~~~~~~~~~~~~~~~~
node_modules/ng-multiselect-dropdown/ng-multiselect-dropdown.module.d.ts:10:21 - error TS2694: Namespace '"C:/MSDE/masthans/Hulk_UI/bifrost_hulk_new_1/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

10     static ɵfac: i0.ɵɵFactoryDeclaration<NgMultiSelectDropDownModule, never>;
                       ~~~~~~~~~~~~~~~~~~~~
_modules/@angular/core/core"' has no exported member 'ɵɵNgModuleDeclaration'.

11     static ɵmod: i0.ɵɵNgModuleDeclaration<NgMultiSelectDropDownModule, [typeof i1.MultiSelectComponent, typeof i2.ClickOutsideDirective, typeof i3.ListFilterPipe], [typeof i4.CommonModule, typeof i5.FormsModule], [typeof i1.MultiSelectComponent]>;
                       ~~~~~~~~~~~~~~~~~~~~~
node_modules/ng-multiselect-dropdown/ng-multiselect-dropdown.module.d.ts:12:21 - error TS2694: Namespace '"C:/MSDE/masthans/Hulk_UI/bifrost_hulk_new_1/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'.

12     static ɵinj: i0.ɵɵInjectorDeclaration<NgMultiSelectDropDownModule>;
                       ~~~~~~~~~~~~~~~~~~~~~
 

**Steps to reproduce**:

**Expected result**:

**Actual result**:

**Demo**: Please share sample code link using StackBlitz or codesandbox

Any relevant code:
```

```

**Comment by masthanshaik675** [comment]
it looks like ng-multiselect-dropdown 1.0.0 version compatible with angular 16. As I am using Angular 8/9 , getting these errors. After I used 0.3.9 version , it working as expected.
